services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-demo
    ports:
      - "5678:5678"
    environment:
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Europe/Paris
      - N8N_CUSTOM_EXTENSIONS=/home/node/custom-nodes
    volumes:
      - n8n_data:/home/node/.n8n
      - ../:/home/node/custom-nodes/n8n-nodes-templatefox
    restart: unless-stopped

volumes:
  n8n_data:
